services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    env_file: .env
    ports:
      - "5080:5000"
    depends_on:
      - r-analytics
    volumes:
      - ./web:/app/web:ro
      - ./app.py:/app/app.py:ro
      - ./data:/app/data:rw
  r-analytics:
    build:
      context: ./r
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
